# This file is used by the aws_setup.py script when setting up the AWS infrastructure to run Wukong.

# This is the region in which we'll be creating the AWS infrastructure. 
aws_region: us-east-1

# These settings are used when setting up the Virtual Private Cloud (VPC) used by Wukong.
# For certain settings, it is recommended to leave them with their default value unless you definitely have a reason to change them.
# This will be indicated in a comment above the corresponding setting/option.
vpc:
  # This controls the range of IPv4 addresses within the VPC specified in CIDR format. 
  # Block sizes must be between a /16 and a /28 netmask. Best to leave this as its default value.
  CidrBlock: 10.0.0.0/16

  PublicSubnetCidrBlock: 10.0.64.0/19

  # These are the CIDR blocks which will be used when creating the private subnets (used by AWS Lambda functions).
  # Important Note: the number of CIDR blocks specified here controls the number of private subnets created.
  #PrivateSubnetCidrBlocks:
  #  - 10.0.32.0/19
  #  - 10.0.0.0/19
  
  # Name of security group for AWS Lambda functions.
  #
  # Max length: 64 characters.  
  #lambda_security_group_name: wukong_lambda_security_group

  # Name of security group for AWS EC2 and AWS Fargate.
  #
  # Max length: 64 characters.  
  serverful_security_group_name: wukong_serverful_security_group

# The following configuration is used when setting up the AWS Lambda functions.
aws_lambda:
  # This will be the name of the AWS Lambda function used as Wukong's serverless Executor.
  # Note that this CANNOT be changed once the function is created (you would have to deploy a new function
  # if you wanted to use a different name).
  #
  # Max length: 64 characters.  
  executor_function_name: WukongExecutor

  # This will be the name of the AWS Lambda function used as a distributed invoker.
  # Note that this CANNOT be changed once the function is created (you would have to deploy a new function
  # if you wanted to use a different name). 
  #
  # Max length: 64 characters.
  invoker_function_name: WukongInvoker

  # This is the name of the IAM role that will be created for use with the AWS Lambda functions.
  iam_role_name: WukongLambdaRole
  
  # The amount of memory that the function should be configured with (in MB). 
  # Note that this can be changed at any time within the AWS Lambda web console.
  #
  # Minimum value: 128
  # Maximum value: 3008
  function_memory_mb: 3008

  # The maximum duration that the Executor can run before timing out. 
  # Note that this can be changed at any time within the AWS Lambda web console.
  #
  # Minimum value: 1
  # Maximum value: 900
  function_timeout_seconds: 120

# This configuration is for AWS ECS/AWS Fargate. 
ecs:
  # The name of the cluster to be created for Wukong's storage cluster.
  #
  # Max length: 255 characters.
  cluster_name: WukongFargateCluster