language: python
sudo: required
# https://docs.travis-ci.com/user/ci-environment/ to get a modern gcc etc
dist: xenial


# notes from http://conda.pydata.org/docs/travis.html
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same. 
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      export RANDOM_ID=`python -c "from random import choice; print ''.join([choice('1234567890') for i in range(6)])"`; 
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      export RANDOM_ID=`python -c "from random import choice; print(''.join([choice('1234567890') for i in range(6)]))"`; 
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - printenv TRAVIS_PULL_REQUEST
  - printenv TRAVIS_PULL_REQUEST_BRANCH
  - printenv TRAVIS_COMMIT
  - printenv TRAVIS_BRANCH
  - printenv
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest cython nose boto3 PyYAML Click pytest numba
  - source activate test-environment
  - pip install glob2 pylint tornado awscli pylint
  - tests/install_pywren.sh
  - tests/run_pylint.sh

before_script:
  - export EPOCH_STAMP=`date +%s`
  - export BUILD_GUID=`echo $TRAVIS_JOB_NUMBER | sed 's/\./_/g'`_${EPOCH_STAMP}_${RANDOM_ID}
  - echo CLEAN BUILD ID IS $BUILD_GUID
  - export BUCKET_NAME=`echo pywren_travis_$BUILD_GUID | sed 's/_/-/g'`
  - echo $BUCKET_NAME
  - pywren test_config
  - pywren get_aws_account_id
  
script:
  - pywren create_config --lambda_role=pywren_travis_test_$BUILD_GUID --function_name=pywren_travis_$BUILD_GUID --bucket_name=$BUCKET_NAME --sqs_queue=pywren_travis_$BUILD_GUID --standalone_name=pywren_travis_$BUILD_GUID
  - pywren create_role
  - pywren create_bucket
  - pywren create_instance_profile
  - pywren create_queue
  - sleep 10
  - pywren deploy_lambda
  - tests/lambda_tests.sh
  - tests/ec2_standalone_tests.sh
  - tests/ec2_macroreduce_tests.sh
  - tests/cmdline_tests.sh
  
after_script:
  # always make sure we do this cleanup if we can
  - pywren delete_queue
  - pywren delete_lambda
  - pywren delete_instance_profile
  - pywren delete_role
  - pywren delete_bucket
  - pywren standalone terminate_instances

after_failure:
  - pywren delete_queue
  - pywren delete_lambda
  - pywren delete_instance_profile
  - pywren delete_role
  - pywren delete_bucket
  - pywren standalone terminate_instances

env:
  global:
    - secure: "NXt+Ni70refb3MsomErOP9Arnw0C/SkCBIkwmZ4jEB6pTaZzonwjSlssE8fLnIkt3lAba45VcVgPAnqy85AqrUQ1KD9zZuE/R0+3W/qk10i3HJggKQuIVj3vnHn5WvLZw0G/9XHme1E3TE3XjutzzqyY3BKU8k1itogqLLO3UX4E6DoX4TgicQbt2YfODySFC9Jyi97anRoeIt245FXjt1JYRaRbaagFcsPMS5SHsqQno2oTCPi/CPD2txbyBRH2MhmezmwQOVsrsBOVIV97VIFJbdA4liJbFTZurYPFM3xApuZIhq+c4kdX7a1Fef4rrL+tpdW3RIx0qIY7q2XLZU5O8/WvAG/IBKXbEYDDEpoDXGcuIkYvS8VtNN9eBGbFLoGX+hEGNhgdiyPCZRv+ICCcXccIjsC13iXP35chzVy7MXkOdDNypZxa5dv0P3RZujfznj4GGWFoNWiX8YvgezL2QYZFJBbw+1vRL3TUOVeRvYlomd54KDVELsMXJ6KGsAKazyEFe+WP3cDOOxIwKXR6/ChlAiN2FUWISIDn6ALrDWUorVe6Jugi/9BV6wcfV4cN8KXb1pvElX9uOFs/Ux8kV0ddwOwTaWHkNWPDn6jRfTLluLAqCwsIpXLFcH3lwS8Eaw9vosrVb37NtzHGfe3JrG4AZekJfERGUmk2Cvw="
    - secure: "KmpGF9FKLgFD3Bi6bM3LbTagDTQddO6bZapVR5N/MhDlAjuuYLr4k6mjhT0vVugi9xAyHNjq974DnC3KPfwOepiOqTnzke7oP6EX9IG5eXFDPXsEms0ZkbYyQdQMcFmGeV7skMROeKRuaoQnFa/i2O9iVd7elIQYkZuItnU8LGRwM5fWrpQzxh1YtA6pUAgJSokX9S7kf+1n47sj4+yYTfzf8A0AgSSzgcAQR+OQBwwqEC3aoomwF50F86R/xSnc9OzuthK81SudsndlSKDq8yN0ISRFpA5bqjLEgoMsKDdoMnKVwTaGSb4HYjmTG0vpvxzlWG8Vyx8NCRTYTdqYoVxZkAT31k/eHHBb5wzaY70vITat8PxPpjOD45sz6Eyo+v/0Po/o50M9d/EknH5BdV3LkWF6IM9VgrS6ypinHHWUo2tugcNpW3NoqLELZm3mUKhOAl0JjF0zYAM/39pay8J/dPRuAv0BuCNZ1iDMHMAqn4bZJ5nHQ0ZQoplJDHf9AWdeAXMmIqP0yHMy6y5oKnnNRjw0J9mpyZX2Gt9xKepNRo4gDJCN25lLWetgyE65LuObSLSuO6UfLhSsxl0k34+SyCRFR3Y8z3lsiBRnfsNpfZeYbJk0ZMT/v286Jr180UWbq/ouJrRk1XcKaNNUKk6/+qVeE5P1je35zdanBnk="
  matrix:
    - RUN_STANDALONE=true
    - RUN_LAMBDA=true
    - RUN_MACROREDUCE=true
    - RUN_COMMANDLINE=true
