lithops:
    storage: ibm_cos
    storage_bucket: ce-cos
    mode: serverless
    data_cleaner: False

serverless:
    backend: code_engine


ibm:
    iam_api_key: <iamapikey>


code_engine:
    namespace  : 75nd5iv9zir
    region     : us-south
    runtime: cohenjomer/lithops-ce-<git-actor>

ibm_cos:
    region : eu-de
    api_key     : <cos_api_key>
